# -*- coding: utf-8 -*-
"""text-to-image_custom_stableDiffusion_DreamBooth_v2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cbHzrO2se6dTO9n5-gqDjAsbb5pZIdFy
"""

!nvidia-smi

# Commented out IPython magic to ensure Python compatibility.
# %pip install -U autotrain-advanced

PROJECT_NAME = "Dreambooth_SDXL"
MODEL_NAME = "stabilityai/stable-diffusion-xl-base-1.0"
DATA_DIR = "/content/rashmika_photos"
REPO_ID = "kr-manish/text-to-image-sdxl-lora-dreemBooth-rashmika"

from PIL import Image

def image_grid(imgs, rows, cols, resize=256):
    assert len(imgs) == rows * cols

    if resize is not None:
        imgs = [img.resize((resize, resize)) for img in imgs]

    w, h = imgs[0].size
    grid_w, grid_h = cols * w, rows * h
    grid = Image.new("RGB", size=(grid_w, grid_h))

    for i, img in enumerate(imgs):
        x = i % cols * w
        y = i // cols * h
        grid.paste(img, box=(x, y))

    return grid

import glob

imgs = [Image.open(path) for path in glob.glob("/content/rashmika_photos/*.jpg")]
image_grid(imgs, 1, 9)

from huggingface_hub import notebook_login
notebook_login()

!autotrain dreambooth \
--model $MODEL_NAME \
--project-name $PROJECT_NAME \
--image-path $DATA_DIR \
--prompt "A photo of rashmika mehta wearing casual clothes, taking a selfie, and smiling." \
--resolution 1024 \
--batch-size 1 \
--num-steps 300 \
--gradient-accumulation 4 \
--lr 1e-4 \
--fp16 \
--gradient-checkpointing \
--push-to-hub \
--repo-id $REPO_ID

from diffusers import DiffusionPipeline, AutoencoderKL, StableDiffusionXLImg2ImgPipeline

import torch

vae = AutoencoderKL.from_pretrained(
    "madebyollin/sdxl-vae-fp16-fix",
    torch_dtype=torch.float16
)
pipe = DiffusionPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    vae=vae,
    torch_dtype=torch.float16,
    variant="fp16",
    use_safetensors=True,
)
pipe.to("cuda");
#pipe.load_lora_weights(REPO_ID, weight_name="pytorch_lora_weights.safetensors")
pipe.load_lora_weights("/content/Dreambooth_SDXL", weight_name="/content/Dreambooth_SDXL/pytorch_lora_weights.safetensors")


prompt = "A photo of rashmika mehta participating in a marathon."

image = pipe(prompt=prompt, num_inference_steps=25, num_images_per_prompt = 3)
image_grid(image.images, 1, 3)

import gc
gc.collect()
torch.cuda.empty_cache()

#prompt = "A photo of manish kumar giving a press conference."
prompt = "A photo of rashmika mehta waring  a indian army clothes."

image = pipe(prompt=prompt, num_inference_steps=25, num_images_per_prompt = 3)
image_grid(image.images, 1, 3)

prompt = "A photo of rashmika mehta is swimming in ocean."

seed = 65
generator = torch.Generator("cuda").manual_seed(seed)
image = pipe(prompt=prompt, num_inference_steps=25, generator=generator).images[0]
image.resize((300, 300))

refiner = StableDiffusionXLImg2ImgPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-refiner-1.0",
    vae=vae,
    torch_dtype=torch.float16,
    use_safetensors=True,
    variant="fp16",
)
refiner.to("cuda");

image = refiner(prompt=prompt, num_inference_steps=25, generator=generator, image=image)
image.images[0].resize((300, 300))

from google.colab import drive
drive.mount('/content/gdrive')
!ln -s /content/gdrive/My\ Drive/ /mydrive
!ls /mydrive

!cp -r /content/rashmika_photos /content/gdrive/MyDrive/text-to-image_sdxl_dreamBooth_custom/rashmika_trained_model_dataa

